WebApp/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class StudentController : Controller
    {
        private ApplicationDbContext _context;

        public StudentController()
        {
            _context = new ApplicationDbContext();
            _context.Users.ToList();
        }
        // GET: Students
        public ActionResult Index()
        {
            var users = _context.Users.ToList();
            return View(users);
        }

        public ActionResult Info(string id)
        {

            var user = _context.Users.FirstOrDefault(o => o.Id == id);
            var books = _context.Books.ToList().Where(o => o.User == user.UserName).ToList();
            if (books != null)
            {
                return View(books);
            }
            
            return RedirectToAction("Idex","Book");
        }

        public ActionResult DeleteStudent(string id)
        {
            var student = _context.Users.FirstOrDefault(o => o.Id == id);
            ApplicationUser message = null;
            if (student != null && student.Count==0)
            {
                message = _context.Users.Remove(student);
                _context.SaveChanges();
            }
            return View(message);
        }
    }
}

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – Библиотека </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body >
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Библиотека", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            
            <div class="navbar-collapse collapse">
                @if (Request.IsAuthenticated)
                {
                <ul class="nav navbar-nav">
                    @if (User.Identity.Name == "11051969dahul@mail.ru")
                    {
                        <li>@Html.ActionLink("Студенты", "Index", "Student")</li>
                        <li>@Html.ActionLink("Добавить студента", "Register", "Account")</li>
                    }

                    <li>@Html.ActionLink("Книги", "Index", "Book")</li>
                    <li>@Html.ActionLink("О программе", "About", "Home")</li>
                    <li>@Html.ActionLink("Контакт", "Contact", "Home")</li>
                </ul>
                    
                }
                    @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – приложение ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>